import {
    PLACEHOLDER,
    SHADES,
    INITIAL_PALETTE,
    PALETTES,
    TAILWIND_CLASSES,
    GRADIENT_DIRECTIONS,
    VIA_OPTIONS,
    INITIAL_GRADIENT
} from './ui.ts'

import { ROUTES } from './routes.ts'

export {
    PLACEHOLDER,
    SHADES,
    INITIAL_PALETTE,
    PALETTES,
    TAILWIND_CLASSES,
    GRADIENT_DIRECTIONS,
    VIA_OPTIONS,
    INITIAL_GRADIENT,
    ROUTES
}
