import {
    PLACEHOLDER,
    SHADES,
    INIT_PALETTE,
    PALETTES,
    TAILWIND_CLASSES,
    GRADIENT_DIRECTIONS,
    VIA_OPTIONS
} from './ui.ts'

import { ROUTES } from './routes.ts'

export {
    PLACEHOLDER,
    SHADES,
    INIT_PALETTE,
    PALETTES,
    TAILWIND_CLASSES,
    GRADIENT_DIRECTIONS,
    VIA_OPTIONS, ROUTES
}
